---
- name: Set Dockerfile
  copy:
    src: "{{ role_path }}/files/Dockerfile"
    dest: /docker-tmp/
    mode: 0644
  tags:
    - deploy

- name: Build image
  shell: cd /docker-tmp/ && docker build -t "{{ containerName }}" .
  tags:
    - deploy
    - build_image

- name: Push image
  shell: docker push "{{ containerName }}"
  tags:
    - deploy
    - push_image

- name: Run container
  shell: sudo docker run -d -p 80:8080 "{{ containerName }}"
  tags:
    - run_image
