---
- name: Set Dockerfile
  copy:
    src: "{{ role_path }}/files/Dockerfile"
    dest: /var/lib/jenkins/docker-tmp/
    mode: 0644
  tags:
    - deploy

- name: Build image
  shell: cd /docker-tmp/ && docker build -t buldozer232/spring-boot .
  tags:
    - deploy
    - build_image

- name: Push image
  shell: docker push buldozer232/spring-boot
  tags:
    - deploy
    - push_image

- name: Run container
  shell: sudo docker run -d -p 80:8080 buldozer232/spring-boot
  tags:
    - run_image
