---
 - name: Pull container
   shell: sudo docker pull {{ container }}
   tags:
     - run_image

 - name: Run container
   shell: sudo docker run -d -p {{ port }}:8080 {{ container }}
   tags:
     - run_image
